excluded:
  - Pods

whitelist_rules:
- void_return
- force_cast
- weak_delegate
- unused_optional_binding
- unused_enumerated
- unused_closure_parameter
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- type_name
- trailing_semicolon
- trailing_newline
- trailing_comma
- syntactic_sugar
- switch_case_alignment
- statement_position
- shorthand_operator
- return_arrow_whitespace
- redundant_void_return
- redundant_string_enum_value
- redundant_optional_initialization
- redundant_nil_coalescing
- redundant_discardable_let
- prohibited_super_call
- overridden_super_call
- operator_usage_whitespace
- operator_whitespace
- opening_brace
- contains_over_first_not_nil
- empty_count
- first_where
- object_literal
- number_separator
- notification_center_detachment
- nimble_operator
- nesting
- multiline_parameters
- mark
- literal_expression_end_indentation
- legacy_nsgeometry_functions
- legacy_constructor
- legacy_cggeometry_functions
- leading_whitespace
- large_tuple
- joined_default_parameter
- is_disjoint
- implicit_return
- implicit_getter
- force_unwrapping
- force_try
- for_where
- fatal_error_message
- fallthrough
- explicit_init
- empty_parentheses_with_trailing_closure
- empty_parameters
- empty_enum_arguments
- dynamic_inline
- discouraged_direct_init
- discarded_notification_center_observer
- cyclomatic_complexity
- control_statement
- compiler_protocol_init
- comma
- colon
- closure_spacing
- closure_parameter_position
- closure_end_indentation
- closing_brace
- class_delegate_protocol
- block_based_kvo
- attributes

line_length:
warning: 250

function_parameter_count:
warning: 10

file_length:
warning: 500

type_body_length:
warning: 400
